### ISSUE TITLE
Fix initial setup

### ISSUE THREAD

**Issue by allthesignals** [MAPC/myschoolcommute2#14]
@mzagaja commented:
Ok /bin/setup failed on me with the following errror:
```
== Import CSV Seed Data ==
rails aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "districts" does not exist
LINE 8:                WHERE a.attrelid = '"districts"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
             (SELECT c.collname FROM pg_collation c, pg_type t
               WHERE c.oid = a.attcollation AND t.oid = a.atttypid AND a.attcollation <> t.typcollation),
                     col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"districts"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum

```
I think it's worth trying to use pg_dump to export in Postgres's custom format:

`pg_dump -h db.live.mapc.org -Fc -o -U editor development_database > massbuilds-04-24-2017.dump`

**Comment by allthesignals** [comment]
Now seeing this:
```
rails aborted!
ActiveRecord::ActiveRecordError: cannot update a new record
/Users/mgardner/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.1/lib/active_record/persistence.rb:308:in `update_columns'
/Users/mgardner/myschoolcommute2/app/models/school.rb:64:in `find_intersecting_municipality'
/Users/mgardner/myschoolcommute2/app/models/school.rb:31:in `muni_id'
```

**Comment by allthesignals** [comment]
https://github.com/MAPC/myschoolcommute2/blob/develop/app/models/school.rb#L7 and https://github.com/MAPC/myschoolcommute2/blob/develop/app/models/school.rb#L10 are causing the issue. Removing these for now, need to strategize something going forward...
