### ISSUE TITLE
can't add new school

### ISSUE THREAD

**Issue by allthesignals** [MAPC/myschoolcommute2#55]
error `cannot update a new record`

**Comment by allthesignals** [comment]
Stemming from #21, #71, going to address this in the test driven ™ way!

**Comment by allthesignals** [comment]
```
activerecord (5.0.1) lib/active_record/persistence.rb:308:in `update_columns'
app/models/school.rb:99:in `find_intersecting_municipality'
app/models/school.rb:51:in `muni_id'
administrate (0.7.0) lib/administrate/page/base.rb:27:in `public_send'
administrate (0.7.0) lib/administrate/page/base.rb:27:in `get_attribute_value'
administrate (0.7.0) lib/administrate/page/base.rb:21:in `attribute_field'
administrate (0.7.0) lib/administrate/page/form.rb:15:in `block in attributes'
administrate (0.7.0) lib/administrate/page/form.rb:14:in `map'
administrate (0.7.0) lib/administrate/page/form.rb:14:in `attributes'
administrate (0.7.0) app/views/administrate/application/_form.html.erb:33:in `block in 
```

Looks like administrate is mapping through model attributes which triggers the hook. Removing computed attributes from form field.

**Comment by allthesignals** [comment]
@mzagaja I think there's an optimization issue here. I can get past the logic with the callbacks, but since the callback triggers the walkshed generation, it takes 15 minutes to create the school since the process waits for it to complete. Any thoughts? Is this a Sidekiq task? How would that look since the operation happens mostly in the database.

**Comment by allthesignals** [comment]
Walkshed generation happens here: https://github.com/MAPC/myschoolcommute2/blob/develop/app/queries/walkshed_query.rb

Which is called from here: https://github.com/MAPC/myschoolcommute2/blob/develop/app/models/school.rb#L9.

**Comment by allthesignals** [comment]
I think this might be causing issues, although it actually does classify the columns correctly. https://github.com/MAPC/myschoolcommute2/blob/develop/config/initializers/rgeo.rb#L2

**Comment by allthesignals** [comment]
`PG::InvalidParameterValue: ERROR: Geometry type (Polygon) does not match column type (MultiPolygon)`

**Comment by allthesignals** [comment]
Related #77

**Comment by allthesignals** [comment]
Changing shed column types to Geometry - for some reason the output can be either Polygon or Multipolygon. Postis will reject the output when it is Polygon because the column is defined as MultiPolygon. 

The old app handled this problem through Django: 
https://github.com/MAPC/myschoolcommute/blob/master/survey/models.py#L125-L145

Solution I am using sets the type as Geometry, which can accept both.
